# Generated by Django 4.2.3 on 2023-09-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='img_url',
            field=models.TextField(default=1, verbose_name='Img_url'),
            preserve_default=False,
        ),
    ]
